# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openspend < Formula
  desc "OpenSpend CLI for buyer onboarding and service usage"
  homepage "https://github.com/promptingcompany/openspend-cli"
  version "0.1.0-rc.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/promptingcompany/openspend-cli/releases/download/v0.1.0-rc.4/openspend_0.1.0-rc.4_darwin_amd64.tar.gz"
      sha256 "c033e8baaf6419a051f5f85f5ffda306cb25f308f8b96214af9d517c6c87d4ee"

      define_method(:install) do
        bin.install "openspend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/promptingcompany/openspend-cli/releases/download/v0.1.0-rc.4/openspend_0.1.0-rc.4_darwin_arm64.tar.gz"
      sha256 "2e9dda85e2c5d3b8cb70178757dc56b9372790ab0c543efbd218560b49ea2999"

      define_method(:install) do
        bin.install "openspend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/promptingcompany/openspend-cli/releases/download/v0.1.0-rc.4/openspend_0.1.0-rc.4_linux_amd64.tar.gz"
      sha256 "00fefc844dcd821c175e17623acdfe1e94dae6057d125bf477e4c17f68f555bd"
      define_method(:install) do
        bin.install "openspend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/promptingcompany/openspend-cli/releases/download/v0.1.0-rc.4/openspend_0.1.0-rc.4_linux_arm64.tar.gz"
      sha256 "2c59a205f8e1b9585c2c1ecf74c4b6b0f896ac1d765b8c7912acf7e9dd917256"
      define_method(:install) do
        bin.install "openspend"
      end
    end
  end

  test do
    system "#{bin}/openspend", "version"
  end
end
